app:
  build: ./
  ports:
    - "3000:3000"
  links:
    - db:postgres
  volumes:
    - "./:/app"
  environment:
    POSTGRES_USER: "web"
    POSTGRES_PASSWORD: "password"
db:
  image: postgres:9.4.5
  expose:
    - "5432"
  volumes:
    - link-ingester-db-volume:/var/lib/postgresql/data
  environment:
    POSTGRES_USER: "web"
    POSTGRES_PASSWORD: "password"
